### ISSUE TITLE
Config files does not work and No segmentation

### ISSUE THREAD

**Issue by SeeingFarther** [JayParanjape/Blackbox#1]
Could you please share the configurations you're using for the different datasets? I tried running the default configuration, but the code encountered exceptions due to missing values. I attempted to resolve this independently, preventing the exceptions, but I ended up with incorrect results. Specifically, when running the script inside the eval folder after training on the Kvasir-SEG dataset, I obtained outputs consisting of green images, like the one attached below. I've also included the configuration file I used for reference.

**I did not change anything in the code!**

**Output for image 100_cju1d50a94qf50855wsowacrc.jpg**
Rescaled img
![100_cju1d50a94qf50855wsowacrc jpg (1)](https://github.com/user-attachments/assets/3f470f9a-92ff-41cd-b6a5-10a0b6da3e6a)

Rescaled SAM img
![100_cju1d50a94qf50855wsowacrc jpg](https://github.com/user-attachments/assets/cb175246-e14f-401f-b96d-5b9d7de24708)

Rescaled diff
![100_cju1d50a94qf50855wsowacrc jpg (3)](https://github.com/user-attachments/assets/8073e523-f0d6-40a4-bac8-0bc4dba899f1)

Rescale mask predict
![100_cju1d50a94qf50855wsowacrc jpg (2)](https://github.com/user-attachments/assets/c368b93f-0f10-4345-877f-be828b6b5d99)

[default_works.zip](https://github.com/user-attachments/files/18218512/default_works.zip)

**Environment:**
Ubuntu 22.04
I am using the Conda environment with the YAML configuration you provided. However, I had to change the version of TorchAudio as it caused conflicts with other packages (which is another issue that needs to be fixed). I removed the version requirement in the YAML file, which resolved the problem.

**Comment by SeeingFarther** [comment]
****

**Comment by JayParanjape** [comment]
Hello,
I have pasted the link to model checkpoints and config files for the datasets in the README. Could you please try using those. 

Thanks

**Comment by SeeingFarther** [comment]
Hi, 
Thank you for your response! The checkpoint with the provided configuration resolved the green image issue. However, the results don’t seem to have improved significantly. Do you think there might be other issues affecting the performance?

**Result for 0_cju84aoa3ktwn0755pfl4gfwd.jpg**

rescaled SAM img

![0_cju84aoa3ktwn0755pfl4gfwd jpg](https://github.com/user-attachments/assets/48440526-a7c8-4e7c-b485-b5ee5fa6f2cd)

rescaled preds
![0_cju84aoa3ktwn0755pfl4gfwd jpg (1)](https://github.com/user-attachments/assets/ddec2fbb-6850-4109-ae46-419b0c6482a9)

rescaled gt
![0_cju84aoa3ktwn0755pfl4gfwd jpg (2)](https://github.com/user-attachments/assets/d4829e1b-c706-4128-9dd6-1aa6839a2d67)

rescaled diff
![0_cju84aoa3ktwn0755pfl4gfwd jpg (4)](https://github.com/user-attachments/assets/78507b67-b40a-4f16-a753-afe071dc7290)

rescaled img
![0_cju84aoa3ktwn0755pfl4gfwd jpg (3)](https://github.com/user-attachments/assets/02528b4d-ced9-47b7-992d-fd89fb973fb2)

**Comment by JayParanjape** [comment]
I could think of one reason being that the original SAM is itself performing very poorly for this image and prompt. Maybe using MedSAM as the base model instead of SAM with the same config file and checkpoint can give better result

**Comment by JayParanjape** [comment]
Hello, 
I have updated the config files and checkpoints in the same drive. Please check them again.

**Comment by SeeingFarther** [comment]
Hi,
Checked it now with the updated files on Kvasir-SEG(will check later on the other datasets), it works :)

![Screenshot 2024-12-29 at 10 11 50](https://github.com/user-attachments/assets/f54d87cd-1bc5-4dd4-88df-3c0e692fad8c)

![Screenshot 2024-12-29 at 10 11 43](https://github.com/user-attachments/assets/e2ff50e1-d854-4200-ac14-5eb138dbe465)

![Screenshot 2024-12-29 at 10 11 35](https://github.com/user-attachments/assets/b0de9bfa-198c-4ce7-9054-6c99ae0681d6)

Thanks.
